[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.49.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.49.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --baseURL $URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.49.2"

[context.branch-deploy]
command = "hugo --baseURL $URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.49.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
http://madicetea.com/* https://www.madicetea.me/:splat 301!
https://madicetea.com/* https://www.madicetea.me/:splat 301!
http://www.madicetea.com/* https://www.madicetea.me/:splat 301!
https://www.madicetea.com/* https://www.madicetea.me/:splat 301!
http://madicetea.me/* https://www.madicetea.me/:splat 301!
https://madicetea.me/* https://www.madicetea.me/:splat 301!